# Generated by Django 5.1.7 on 2025-03-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.CharField(max_length=36, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('room_code', models.CharField(max_length=10)),
                ('status', models.CharField(blank=True, max_length=5)),
                ('answer', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserChoice',
        ),
    ]
