# Generated by Django 5.1.7 on 2025-03-26 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticks', '0002_userstatus_delete_userchoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStatus',
            new_name='LearnerStatus',
        ),
    ]
