# Generated by Django 5.1.7 on 2025-03-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticks', '0003_rename_userstatus_learnerstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerstatus',
            name='learner_id',
            field=models.CharField(max_length=36),
        ),
    ]
