# Generated by Django 5.1.7 on 2025-03-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticks', '0004_alter_learnerstatus_learner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerstatus',
            name='learner_id',
            field=models.CharField(max_length=50),
        ),
    ]
